import {
  BiBookAdd,
  BiBookContent,
  BiCartAlt,
  BiCog,
  BiPurchaseTagAlt,
  BiStore,
} from 'react-icons/bi';

export const LinkMenuSide = [
  { name: 'Store', path: '/store', icon: <BiStore size={22} /> },
  { name: 'Product', path: '/product', icon: <BiBookAdd size={22} /> },
  { name: 'Category', path: '/category', icon: <BiBookContent size={22} /> },
  { name: 'Order', path: '/order', icon: <BiCartAlt size={22} /> },
  { name: 'Promotion', path: '/promotion', icon: <BiPurchaseTagAlt size={22} /> },
  { name: 'Setting', path: '/setting', icon: <BiCog size={22} /> },
];

export const themeColors = [
  {
    name: 'blue-theme',
    color: '#1A97F5',
  },
  {
    name: 'green-theme',
    color: '#03C9D7',
  },
  {
    name: 'purple-theme',
    color: '#7352FF',
  },
  {
    name: 'red-theme',
    color: '#FF5C8E',
  },
  {
    name: 'indigo-theme',
    color: '#1E4DB7',
  },
  {
    color: '#FB9678',
    name: 'orange-theme',
  },
];

export const DataUser = [
  {
    id: 'userId1',
    userName: 'Nguyen Cong Hau',
    phone: '0946111122',
    email: 'hau2803nch@gmail.com',
    password: '***********',
    token: '**********',
    avatar: {
      _id: 'imageId1',
      name: 'Image1',
      src: 'https://chocanh.vn/wp-content/uploads/cho-husky-sibir-ngao-2.jpg',
      type: 'png',
    },
    role: 'Admin',
    isAdmin: true,
    isShipper: true,
    addresses: [
      {
        lat: '41.40338',
        long: '2.17403',
        address: '201/20 Nguyen Thai Son',
        name: 'Home',
      },
      {
        lat: '41.40338',
        long: '2.17403',
        address: '200 Duong Quang Ham',
        name: 'Truong VLU',
      },
    ],
    dob: '2001-28-03T09:17:54.759Z',
    gender: 'Male',
    codeValidate: 'code88aaabcdjcskdcd112',
    promotions: ['promotionId1'],
    shipperHistories: ['shipperId1', 'shipperId2'],
    recentAt: '2022-09-03T09:17:54.759Z',
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
    status: 'ACTIVE',
  },
];

export const DataStore = [
  {
    _id: 'storeId1',
    name: 'Cơm gà xối mỡ chị 7',
    slug: 'com-ga-xoi-mo-chi-7',
    desc: 'Đây là cửa hàng lâu đời với món ...',
    phone: '09888888888',
    images: [
      {
        _id: 'imageId1',
        name: 'Image1',
        src: 'https://chocanh.vn/wp-content/uploads/cho-husky-sibir-ngao-2.jpg',
        type: 'png',
        updatedAt: null,
        createdAt: '2022-09-03T09:17:54.759Z',
        createdBy: 'hau2803nch@gmail.com',
        updatedBy: null,
        status: 'ACTIVE',
      },
    ],
    location: {
      lat: '41.40338',
      long: '2.17403',
      address: '120 Dương Quảng Hàm',
    },
    categories: ['categoryId1', 'categoryId3', 'categoryId3'],
    products: ['productId1', 'productId2'],
    vi: 'storeId1',
    priceShipKm: 10,
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
    status: 'ACTIVE',
  },
  {
    _id: 'storeId1',
    name: 'Cơm gà xối mỡ chị 7',
    slug: 'com-ga-xoi-mo-chi-7',
    desc: 'Đây là cửa hàng lâu đời với món ...',
    phone: '09888888888',
    images: [
      {
        _id: 'imageId1',
        name: 'Image1',
        src: 'https://chocanh.vn/wp-content/uploads/cho-husky-sibir-ngao-2.jpg',
        type: 'png',
        updatedAt: null,
        createdAt: '2022-09-03T09:17:54.759Z',
        createdBy: 'hau2803nch@gmail.com',
        updatedBy: null,
        status: 'ACTIVE',
      },
    ],
    location: {
      lat: '41.40338',
      long: '2.17403',
      address: '120 Dương Quảng Hàm',
    },
    categories: ['categoryId1', 'categoryId3', 'categoryId3'],
    products: ['productId1', 'productId2'],
    vi: 'storeId1',
    priceShipKm: 10,
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
    status: 'ACTIVE',
  },
  {
    _id: 'storeId1',
    name: 'Cơm gà xối mỡ chị 7',
    slug: 'com-ga-xoi-mo-chi-7',
    desc: 'Đây là cửa hàng lâu đời với món ...',
    phone: '09888888888',
    images: [
      {
        _id: 'imageId1',
        name: 'Image1',
        src: 'https://chocanh.vn/wp-content/uploads/cho-husky-sibir-ngao-2.jpg',
        type: 'png',
        updatedAt: null,
        createdAt: '2022-09-03T09:17:54.759Z',
        createdBy: 'hau2803nch@gmail.com',
        updatedBy: null,
        status: 'ACTIVE',
      },
    ],
    location: {
      lat: '41.40338',
      long: '2.17403',
      address: '120 Dương Quảng Hàm',
    },
    categories: ['categoryId1', 'categoryId3', 'categoryId3'],
    products: ['productId1', 'productId2'],
    vi: 'storeId1',
    priceShipKm: 10,
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
    status: 'ACTIVE',
  },
];

export const DataCategory = [
  {
    _id: 'categoryId1',
    parent: 'categoryId2',
    vi: 'categoryId1',
    viName: 'Tra sua',
    'viSlug ': 'tra-sua',
    'viStatus ': 'ACTIVE',
    point: 6,
    salePromotion: 'salePromotionId1',
    expiredSalePromotion: '2022-09-03T09:17:54.759Z',
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedAt: null,
    updatedBy: null,
    status: 'ACTIVE',
  },
];

export const DataCategoryInfo = [
  {
    _id: 'categoryInfoId1',
    name: 'Tra sua',
    desc: "Tra sua la thuc uong 'hot'",
    'slug ': 'tra-sua',
    'status ': 'ACTIVE',
    content: "Tra sua la thuc uong 'hot'",
    image: {
      _id: 'imageId1',
      name: 'Image1',
      src: 'https://img1.png',
      type: 'png',
      updatedAt: null,
      createdAt: '2022-09-03T09:17:54.759Z',
      createdBy: 'hau2803nch@gmail.com',
      updatedBy: null,
      status: 'ACTIVE',
    },
    icon: {
      _id: 'imageId1',
      name: 'Image1',
      src: 'https://img1.png',
      type: 'png',
      updatedAt: null,
      createdAt: '2022-09-03T09:17:54.759Z',
      createdBy: 'hau2803nch@gmail.com',
      updatedBy: null,
      status: 'ACTIVE',
    },
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedAt: null,
    updatedBy: null,
    status: 'ACTIVE',
  },
];

export const DataPromotion = [
  {
    _id: 'productId1',
    code: 'MAGIAMGIA_020922',
    name: 'Ma giam gia 2/9',
    type: 'Promotion || Discount',
    startTime: '2022-09-03T09:17:54.759Z',
    endTime: '2022-09-03T09:17:54.759Z',
    icon: {
      _id: 'imageId1',
      name: 'Image1',
      src: 'https://img1.png',
      type: 'png',
    },
    percent: 5,
    price: 0,
    isFreeship: false,
    lang: 'vi',
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
    status: 'ACTIVE',
  },
];

export const DataOrder = [
  {
    _id: 'transactionId1',
    orderId: 'O-NCH-DDMMYY-OKI5',
    transactionId: 'transactionId2',
    status: 2,
    statusName: 'DELIVERY',
    phone: '0977776654',
    note: 'Giao hang nhanh nhe!',
    location: {
      lat: '41.40338',
      long: '2.17403',
      address: 'Lầu 8 VLU CS3',
    },
    deliveryPrice: 10000,
    totalAmount: 52000,
    totalAmountTemporary: 52000,
    promotion: null,
    totalPromotion: 0,
    customer: 'customerId3',
    shipper: 'shipperId10',
    qr: 'https://davidshimjs.github.io/qrcodejs/ ',
    orderItems: [
      {
        _id: 'orderItemId1',
        orderId: 'orderId9',
        productId: 'productId7',
        price: 30000,
        quantity: 1,
        image: 'https://product.png',
        updatedAt: null,
        createdAt: '2022-09-03T09:17:54.759Z',
        createdBy: 'hau2803nch@gmail.com',
        updatedBy: null,
        status: 'ACTIVE',
      },
      {
        _id: 'orderItemId2',
        orderId: 'orderId3',
        productId: 'productId3',
        price: 10000,
        image: 'https://product.png',
        quantity: 1,
        updatedAt: null,
        createdAt: '2022-09-03T09:17:54.759Z',
        createdBy: 'hau2803nch@gmail.com',
        updatedBy: null,
        status: 'ACTIVE',
      },
    ],
    images: [],
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
  },
];

export const DataTransaction = [
  {
    _id: 'transactionId1',
    type: 0,
    name: 'Thanh toan khi nhan hang',
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
    status: 'ACTIVE',
  },
];

export const DataOrderItem = [
  {
    _id: 'orderItemId1',
    orderId: 'orderId9',
    productId: 'productId7',
    price: 30000,
    quantity: 1,
    image: 'https://product.png',
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
    status: 'ACTIVE',
  },
];

export const DataShipper = [
  {
    _id: 'shipperId1',
    shipper: 'userId1',
    orders: ['orderId9', 'orderId2'],
    updatedAt: null,
    createdAt: '2022-09-03T09:17:54.759Z',
    createdBy: 'hau2803nch@gmail.com',
    updatedBy: null,
    status: 'ACTIVE',
  },
];
